version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env.bd
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net-db
    restart:
      unless-stopped

      # https://github.com/MerLant/HshBack.git
  backend:
    env_file:
      - .env.back
      - .env.db
    build:
      context: /Users/merlant/Developer/HshBack/
      dockerfile: Dockerfile
    depends_on:
      - db
      - piston
    networks:
      - net-backend
      - net-db
    restart: unless-stopped
    ports:
      - "3000:3000"

    # https://github.com/MerLant/Hsh.git#main
  frontend:
    build:
      context: /Users/merlant/Developer/Hsh/
      dockerfile: Dockerfile
    env_file:
      - .env.front
    networks:
      - net-frontend
    depends_on:
      - backend

  request-sender:
    image: ubuntu
    networks:
      - net-backend
    entrypoint: ["/bin/sh", "-c"]
    command: |
      apt-get update && apt-get install -y wget &&
      wget --method=POST --body-data='{"language": "dotnet", "version": "5.x"}' \
      --header='Content-Type: application/json' \
      http://piston:2000/api/v2/packages -O -
    depends_on:
      - piston

  piston:
    image: ghcr.io/engineer-man/piston
    networks:
      - net-backend
    volumes:
      - ./local_piston:/piston
      - type: tmpfs
        target: /piston/jobs
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - net-frontend
      - net-backend

  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

volumes:
  pgdata:

networks:
  net-backend:
  net-frontend:
  net-db:
